services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mountebank:
    image: bbyars/mountebank:latest
    ports:
      - "2525:2525"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./imposter:/imposter
    command: --configfile /imposter/mountebank.json --allowInjection

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProjetoFinalDB;User Id=sa;Password=StrongPass123!;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
      - Jwt__Key=ChaveSecretaMuitoLongaParaJWT2026AntonioDario!
      - Jwt__Issuer=ApiAntonioDario
      - Jwt__Audience=ApiAntonioDarioUsers
    depends_on:
      - sqlserver
      - redis
      - mountebank

volumes:
  sqldata: