CREATE DATABASE ProjetoFinalDB;
GO
USE ProjetoFinalDB;
GO

CREATE TABLE Utilizadores (
    Id        INT IDENTITY(1,1) PRIMARY KEY,
    Nome      NVARCHAR(100) NOT NULL,
    Email     NVARCHAR(150) NOT NULL UNIQUE,
    Password  NVARCHAR(255) NOT NULL,
    Role      NVARCHAR(50)  NOT NULL DEFAULT 'User',
    CriadoEm DATETIME2     NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE Produtos (
    Id        INT IDENTITY(1,1) PRIMARY KEY,
    Nome      NVARCHAR(150) NOT NULL,
    Descricao NVARCHAR(500),
    Preco     DECIMAL(10,2) NOT NULL,
    Stock     INT           NOT NULL DEFAULT 0,
    SKU       NVARCHAR(50)  NOT NULL UNIQUE,
    CriadoEm DATETIME2     NOT NULL DEFAULT GETUTCDATE()
);