FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ApiAntonioDarioProjetoFinal/ApiAntonioDarioProjetoFinal.csproj ./ApiAntonioDarioProjetoFinal/
RUN dotnet restore ApiAntonioDarioProjetoFinal/ApiAntonioDarioProjetoFinal.csproj
COPY . .
RUN dotnet publish ApiAntonioDarioProjetoFinal/ApiAntonioDarioProjetoFinal.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ApiAntonioDarioProjetoFinal.dll"]