FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY api/ApiAntonioDarioProjetoFinal/ApiAntonioDarioProjetoFinal.csproj \
     api/ApiAntonioDarioProjetoFinal/
RUN dotnet restore api/ApiAntonioDarioProjetoFinal/ApiAntonioDarioProjetoFinal.csproj

COPY . .
WORKDIR /src/api/ApiAntonioDarioProjetoFinal
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "ApiAntonioDarioProjetoFinal.dll"]